[workspace]
channels = ["conda-forge"]
name = "esicm-26-team-airgorithms"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
hmm = "python Agent_B/hmm_ventilation_phase_inference.py"
lab = "jupyter lab"

[dependencies]
python = "3.12.*"
numpy = ">=2.4.1,<3"
pandas = ">=3.0.0,<4"
scikit-learn = ">=1.8.0,<2"
pyarrow = ">=23.0.0,<24"
matplotlib = ">=3.10.8,<4"
jupyter = ">=1.1.1,<2"
ipykernel = ">=7.1.0,<8"
hmmlearn = ">=0.3.3,<0.4"
